version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8082:80"
    restart: always
    networks:
      - Machines_default

  backend:
    environment:
      - PYTHONUNBUFFERED=1
    build: ./flask-backend
    ports:
      - "8002:8002"
    restart: always
    env_file: .env
    networks:
      - Machines_default
      - csc2033_team32_25-26_default
    volumes:
      - ./uploads:/app/static/uploads

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    command: tunnel run
    restart: always
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - Machines_default
      - csc2033_team32_25-26_default

networks:
  Machines_default:
    external: true
  csc2033_team32_25-26_default:
    external: true
